run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - nilerr
    - exportloopref

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/rootsploit/reconator

  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - errcheck
        - bodyclose

    # Exclude template files
    - path: internal/report/templates\.go
      linters:
        - misspell

    # Allow error shadowing in certain patterns
    - linters:
        - govet
      text: "shadow: declaration of \"err\""

  max-issues-per-linter: 50
  max-same-issues: 10

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
