name: Feature Request
description: Suggest a new feature for Reconator
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like
      placeholder: I would like Reconator to...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Why would this feature be useful? What problem does it solve?
      placeholder: This would help with...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried...

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area of Reconator does this relate to?
      options:
        - Subdomain Enumeration
        - Port Scanning
        - Vulnerability Scanning
        - AI/Intelligence
        - Reporting
        - Screenshot/Visual
        - Performance
        - Configuration
        - CLI/UX
        - Other
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation
      description: If you have ideas on how to implement this, share them here
      placeholder: This could be implemented by...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
